### ISSUE TITLE
Any plans on this provider?

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/provider-jet-opentelekomcloud#2]
Hey,

i just stumbled across this project. We are currently using crossplane on aws and are evaluating otc. This provider would really help us. So i was just wondering if there are any plans on getting this running? 

I would offer help but i am not that familiar with golang yet and can't even get this running locally. :(

Thanks,
Björn

**Comment by vladimirvshivkov** [comment]
Hi,

This project is not our primary focus, but it used to be running.
I guess it needs terraform provider update.
I will have a look at it.

**Comment by bbung** [comment]
Issues where cause by my go version. The problem seems to be upstream https://github.com/crossplane-contrib/provider-jet-template/issues/29 .

Go Version v1.17 works.
